# Generated by Django 5.0.6 on 2026-05-29 14:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('residence', models.CharField(max_length=200)),
                ('parent_guardian_name', models.CharField(max_length=200)),
                ('parent_guardian_phone', models.CharField(max_length=20)),
                ('parent_guardian_email', models.EmailField(blank=True, max_length=254)),
                ('parent_guardian_relation', models.CharField(default='Guardian', max_length=50)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/students/')),
                ('total_fees_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.schoolclass')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['student_id'], name='students_st_student_e7126a_idx'), models.Index(fields=['full_name'], name='students_st_full_na_6ea9f7_idx'), models.Index(fields=['current_class'], name='students_st_current_ad0594_idx'), models.Index(fields=['gender'], name='students_st_gender_e01d54_idx')],
            },
        ),
    ]
