# Generated by Django 5.0.6 on 2026-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='For mobile money or bank transfer', max_length=100)),
                ('payment_date', models.DateTimeField()),
                ('academic_year', models.CharField(max_length=10)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('note_file', models.FileField(blank=True, null=True, upload_to='payment_notes/')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('cheque_image', models.ImageField(blank=True, null=True, upload_to='receipts/cheques/')),
                ('finance_approved_at', models.DateTimeField(auto_now_add=True)),
                ('finance_notes', models.TextField(blank=True)),
                ('hm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hm_signature_image', models.ImageField(blank=True, null=True, upload_to='receipts/signatures/')),
                ('it_admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('it_admin_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_FINANCE', 'Pending Finance Approval'), ('PENDING_IT', 'Pending IT Admin Approval'), ('APPROVED', 'Approved (Final)'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING_FINANCE', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
