# Generated by Django 5.0.6 on 2026-05-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentledger',
            name='finance_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentledger',
            name='hm_approval_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hm_approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentledger',
            name='it_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentledger',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='payments.paymentledger'),
        ),
        migrations.AddField(
            model_name='paymentledger',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_ledger_entries', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='paymentledger',
            index=models.Index(fields=['student', '-created_at'], name='payments_pa_student_67d98c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentledger',
            index=models.Index(fields=['status'], name='payments_pa_status_726f99_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentledger',
            index=models.Index(fields=['academic_year'], name='payments_pa_academi_170820_idx'),
        ),
    ]
