# Generated by Django 5.0.6 on 2026-05-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('residence', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('staff_type', models.CharField(choices=[('TEACHING', 'Teaching'), ('NON_TEACHING', 'Non-Teaching')], default='TEACHING', max_length=20)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/teachers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='classes.schoolclass')),
                ('classes_taught', models.ManyToManyField(blank=True, related_name='subject_teachers', to='classes.schoolclass')),
                ('subjects_taught', models.ManyToManyField(blank=True, related_name='teachers', to='classes.subject')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
