# Generated by Django 5.0.6 on 2026-05-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['employee_id'], name='teachers_te_employe_8033d0_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['full_name'], name='teachers_te_full_na_e7daa7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['gender'], name='teachers_te_gender_ff07d7_idx'),
        ),
    ]
