# Generated by Django 5.0.6 on 2026-05-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examreminder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='asst_headmaster_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asst_hm_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='class_teacher_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.subject'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_results', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='examreminder',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='exams.examsession'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', '-created_at'], name='exams_examr_student_d606e4_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['teacher', '-created_at'], name='exams_examr_teacher_ae5fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['status'], name='exams_examr_status_7af682_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'subject', 'exam_session')},
        ),
    ]
